services:
  app:
    build:
      args:
        user: paul
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: portal-pago
    container_name: app-portal-pagos
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./logs/php.log:/var/log/fpm-php.www.log
    networks:
      - app-network

  db:
    container_name: app-mysql
    restart: unless-stopped
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - app-network

  web:
    container_name: app-nginx-portal
    restart: unless-stopped
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./logs/nginx:/var/log/nginx/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge